package org.demo.model.mbg;

import java.util.Date;

public class Blog {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blog.FID
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blog.FTitle
     *
     * @mbg.generated
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blog.FContent
     *
     * @mbg.generated
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blog.FDate
     *
     * @mbg.generated
     */
    private Date date;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blog.FAuthorID
     *
     * @mbg.generated
     */
    private Integer authorid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blog.FID
     *
     * @return the value of t_blog.FID
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blog.FID
     *
     * @param id the value for t_blog.FID
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blog.FTitle
     *
     * @return the value of t_blog.FTitle
     *
     * @mbg.generated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blog.FTitle
     *
     * @param title the value for t_blog.FTitle
     *
     * @mbg.generated
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blog.FContent
     *
     * @return the value of t_blog.FContent
     *
     * @mbg.generated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blog.FContent
     *
     * @param content the value for t_blog.FContent
     *
     * @mbg.generated
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blog.FDate
     *
     * @return the value of t_blog.FDate
     *
     * @mbg.generated
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blog.FDate
     *
     * @param date the value for t_blog.FDate
     *
     * @mbg.generated
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blog.FAuthorID
     *
     * @return the value of t_blog.FAuthorID
     *
     * @mbg.generated
     */
    public Integer getAuthorid() {
        return authorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blog.FAuthorID
     *
     * @param authorid the value for t_blog.FAuthorID
     *
     * @mbg.generated
     */
    public void setAuthorid(Integer authorid) {
        this.authorid = authorid;
    }
}