package org.demo.model.mbg;

public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.FID
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.FPassword
     *
     * @mbg.generated
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.FUsername
     *
     * @mbg.generated
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.FTruename
     *
     * @mbg.generated
     */
    private String truename;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.FID
     *
     * @return the value of t_user.FID
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.FID
     *
     * @param id the value for t_user.FID
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.FPassword
     *
     * @return the value of t_user.FPassword
     *
     * @mbg.generated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.FPassword
     *
     * @param password the value for t_user.FPassword
     *
     * @mbg.generated
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.FUsername
     *
     * @return the value of t_user.FUsername
     *
     * @mbg.generated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.FUsername
     *
     * @param username the value for t_user.FUsername
     *
     * @mbg.generated
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.FTruename
     *
     * @return the value of t_user.FTruename
     *
     * @mbg.generated
     */
    public String getTruename() {
        return truename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.FTruename
     *
     * @param truename the value for t_user.FTruename
     *
     * @mbg.generated
     */
    public void setTruename(String truename) {
        this.truename = truename;
    }
}